name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Build using rush
      - name: Rush install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose
      - name: Rush deploy
        run: node common/scripts/install-run-rush.js deploy

      # Setup AWS
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::257838883645:role/GitHub
          aws-region: us-east-1
          output-credentials: true

      - name: Install Amazon ECR Docker Credential Helper # Requried to securly log in to AWS ECR. `docker login` with `aws ecr get-login-password` is insecure.
        run: |
          sudo apt-get update
          sudo apt-get install -y amazon-ecr-credential-helper

      - name: Configure Docker to use ECR Credential Helper
        run: |
          mkdir -p ~/.docker
          echo '{"credsStore": "ecr-login"}' > ~/.docker/config.json

      # Setup Porter
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0

      # Setup Infisical
      - name: Install Infisical CLI
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical
          INFISICAL_TOKEN="$(infisical login --method=universal-auth --client-id=${{ secrets.INFISICAL_CLIENT_ID }} --client-secret=${{ secrets.INFISICAL_CLIENT_SECRET }} --domain https://strada-temp-1-service-3887-51be8161-ruo3m20i.onporter.run/api --plain --silent)"
          echo "INFISICAL_TOKEN=$INFISICAL_TOKEN" >> $GITHUB_ENV

      # Deploy databases
      - name: Push Docker image - databases-db
        env:
          ECR_REGISTRY: 257838883645.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: databases-db
          INFISICAL_TOKEN: ${{ env.INFISICAL_TOKEN }}
        run: |
          MAIN_WORK_DIR=$PWD
          cd databases/db
          chmod 744 docker-build.sh
           ./docker-build.sh --image_name $ECR_REGISTRY/$ECR_REPOSITORY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
          cd $MAIN_WORK_DIR

      - name: Deploy Porter stack - databases-db-one-off
        timeout-minutes: 30
        run: exec porter app update-tag databases-db-one-off --tag latest --wait
        env:
          PORTER_CLUSTER: 3917
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_PROJECT: 10773
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN }}

      - name: Deploy Porter stack - databases-db-one-off migrate
        timeout-minutes: 30
        run: exec porter app run databases-db-one-off --job databases-db-one-off-service --wait
        env:
          PORTER_CLUSTER: 3917
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_PROJECT: 10773
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN }}

      # Deploy servers
      - name: Push Docker image - servers-express
        env:
          ECR_REGISTRY: 257838883645.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: servers-express
          INFISICAL_TOKEN: ${{ env.INFISICAL_TOKEN }}
        run: |
          MAIN_WORK_DIR=$PWD
          cd common/deploy/servers/express
          chmod 744 docker-build.sh
          ./docker-build.sh --image_name $ECR_REGISTRY/$ECR_REPOSITORY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
          cd $MAIN_WORK_DIR

      - name: Deploy Porter stack - servers-express
        timeout-minutes: 30
        run: exec porter app update-tag servers-express --tag latest
        env:
          PORTER_CLUSTER: 3917
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_PROJECT: 10773
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN }}

      # Deploy clients
      - name: Deploy to S3
        run: aws s3 sync clients/vite/dist/ s3://vite-react-app-ci --delete
        env:
          AWS_REGION: us-east-1
